"""empty message

Revision ID: 081baf2a0759
Revises: aaefdaadfb13
Create Date: 2020-04-09 22:26:34.042922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081baf2a0759'
down_revision = 'aaefdaadfb13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
